---
title: "ADA Final Project"
author: "Katie Wojcik"
date: "2022-11-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# open packages
library(haven)
library(tidyverse)
library(ggplot2)
library(odds.n.ends)
pacman::p_load(odds.n.ends, blorr, lmtest, car,  broom, tidyverse, jtools)
library(DiagrammeR)
library(table1)
```

```{r}
#import data
nsfg <- read_sav("/Users/katiewojcik19/Desktop/fall 2022/ADA/Project/nsfg.sav")
```

```{r}
#select variables, clean data
nsfg$MORNPILL <- as.factor(nsfg$MORNPILL)
nsfg$CHSUPPOR <- as.factor(nsfg$CHSUPPOR)
nsfg$EVERPREG <- as.factor(nsfg$EVERPREG)
nsfg$VRY1STAG <- as.factor(nsfg$VRY1STAG)
nsfg$ANYBC12 <- as.factor(nsfg$ANYBC12)
nsfg$RELIGION <- as.factor(nsfg$RELIGION)


nsfg.clean <- nsfg%>%
  select(MORNPILL, CHSUPPOR, EVERPREG, ANYBC12, VRY1STAG, RELIGION)%>%
  mutate(MORNPILL = recode_factor(.x = MORNPILL,
                                  '1' = 'Yes',
                                  '5' = 'No'))%>%
  mutate(CHSUPPOR = recode_factor(.x = CHSUPPOR,
                                  '1' = 'Strongly agree',
                                  '2' = 'Agree',
                                  '3' = 'Disagree',
                                  '4' = 'Strongly disagree',
                                  '5' = 'Neither agree nor disagree',
                                  '8' = NA_character_,
                                  '9' = NA_character_))%>%
  mutate(EVERPREG = recode_factor(.x = EVERPREG,
                                  '1' = 'Yes',
                                  '5' = 'No'))%>%
  mutate(ANYBC12 = recode_factor(.x = ANYBC12,
                                 '1' = 'Yes',
                                 '2' = 'No'))%>%
  mutate(RELIGION = recode_factor(.x = RELIGION,
                                  '1' = 'No religion',
                                  '2' = 'Catholic',
                                  '3' = 'Protestant',
                                  '4' = 'Other religions'))%>%
  mutate(VRY1STAG = recode_factor(.x = VRY1STAG,
                                  '10' = NA_character_))

nsfg.clean$VRY1STAG <- as.character(nsfg.clean$VRY1STAG)
nsfg.clean$VRY1STAG <- as.numeric(nsfg.clean$VRY1STAG)

nsfg.clean <- nsfg.clean%>%
  drop_na()
```

```{r}
# boxplot to visualize data

ggplot(data = nsfg.clean) + 
  geom_bar(position = "dodge", mapping = aes(CHSUPPOR, fill = MORNPILL)) +
  labs(x = "Support Single Motherhood?", y = "Frequency", fill = "Ever Used Emergency Contraception") +
  coord_flip()
```

```{r}
#univariate regression model
model1<- glm(MORNPILL ~ CHSUPPOR , data=nsfg.clean, family="binomial")
summary(model1)

odds.n.ends(model1)
## The odds of never using emergency contraception in those who agree that single motherhood is acceptable is 1.67 times higher than those who strongly agree that single motherhood is acceptable after adjusting for history of pregnancy, use of regular birth control, religion, and age at first intercourse (95% CI = 1.46-1.91). 
# The odds of never using emergency contraception in those who disagree that single motherhood is acceptable is 2.66 times higher than those who strongly agree that single motherhood is acceptable after adjusting for history of pregnancy, use of regular birth control, religion, and age at first intercourse (95% CI = 2.10-3.40). 
# The odds of never using emergency contraception in those who strongly disagree that single motherhood is acceptable is 3.76 times higher than those who strongly agree that single motherhood is acceptable after adjusting for history of pregnancy, use of regular birth control, religion, and age at first intercourse (95% CI = 2.40-6.22).
# The odds of never using emergency contraception in those who neither agree nor disagree that single motherhood is acceptable is 2.23 times higher than those who strongly agree that single motherhood is acceptable after adjusting for history of pregnancy, use of regular birth control, religion, and age at first intercourse (95% CI = 1.20-4.54).
```

```{r}
#test linearity assumption for age using box tidwell
nsfg.clean <- nsfg.clean %>%
  mutate(age.times.logage = VRY1STAG * log(VRY1STAG)) # create term to test linearity

model2 <- glm(MORNPILL ~ VRY1STAG + age.times.logage, data=nsfg.clean, family="binomial") 

summary(model2)

# The coefficient is significant, so the linearity assumption is violated. 
```

```{r}
#create categorical variable for age
nsfg.clean <- nsfg.clean %>%
  mutate(age_cat = case_when(VRY1STAG > 10 & VRY1STAG < 15 ~ 1,
                             VRY1STAG >= 15 & VRY1STAG < 20 ~ 2,
                             VRY1STAG >= 20  ~ 3),
         age_cat = factor(age_cat, 1:3, c("11-15", "16-20", "20+"))) #make it as a factor variable

# checking to make sure recode worked
summary(nsfg.clean$age_cat)
by(nsfg.clean$VRY1STAG, nsfg.clean$age_cat, summary)
```

```{r}
#make sure each category has enough cases
table(nsfg.clean$MORNPILL, nsfg.clean$age_cat, nsfg.clean$CHSUPPOR, nsfg.clean$EVERPREG, nsfg.clean$ANYBC12, nsfg.clean$RELIGION)
```


```{r}
# run regression model with new age term
model3<- glm(MORNPILL ~ CHSUPPOR + EVERPREG + ANYBC12 + RELIGION + age_cat, data=nsfg.clean, family="binomial")
summary(model3)

odds.n.ends(model3)

# The odds of never using emergency contraception in those who agree that single motherhood is acceptable is 1.50 times higher than those who strongly agree that single motherhood is acceptable after adjusting for history of pregnancy, use of regular birth control, religion, and age at first intercourse (95% CI = 1.30-1.72). 
# The odds of never using emergency contraception in those who disagree that single motherhood is acceptable is 2.25 times higher than those who strongly agree that single motherhood is acceptable after adjusting for history of pregnancy, use of regular birth control, religion, and age at first intercourse (95% CI = 1.77-2.89). 
# The odds of never using emergency contraception in those who strongly disagree that single motherhood is acceptable is 3.06 times higher than those who strongly agree that single motherhood is acceptable after adjusting for history of pregnancy, use of regular birth control, religion, and age at first intercourse (95% CI = 1.94-5.09).
# The odds of never using emergency contraception in those who neither agree nor disagree that single motherhood is acceptable is 1.70 times higher than those who strongly agree that single motherhood is acceptable after adjusting for history of pregnancy, use of regular birth control, religion, and age at first intercourse (95% CI = 0.91-3.48).
```

```{r}
#multicollinearity assumption 
vif(model3)

# VIF < 10, so assumption is not violated.
```

```{r}
# influential points
# Plot Cooks's Distance
plot(model3, which = 4, id.n = 3, col="red")

#get distances
model3.data <- augment(model3) %>%  
  mutate(index = 1:n()) 

head(model3.data)

## Identify and exclude observations with a Cook's Distance greater than a cutoff, use 3 x the mean Cook's D 
cuttoff <- mean(model3.data$.cooksd)*3 # defines cutoff variable

nsfg_out <- model3.data %>% # excludes observations
  filter(.cooksd<cuttoff)

nrow(nsfg_out)/nrow(nsfg.clean) # check percent kept
#92.05% kept

#model with observations excluded
model4<- glm(MORNPILL ~ CHSUPPOR + EVERPREG + ANYBC12 + RELIGION + age_cat, data=nsfg_out, family="binomial")
summary(model4)

odds.n.ends(model4)

#compare coefficients
compareCoefs(model3, model4) 

#compare variables to original
table(nsfg_out$CHSUPPOR, nsfg_out$MORNPILL)
table(nsfg.clean$CHSUPPOR, nsfg.clean$MORNPILL)

# excluded everyone who disagreed, strongly disagreed, and neither agreed nor disagreed.
# make more realistic cutoffs
cuttoff <- 0.008 # defines cutoff variable

nsfg_out2 <- model3.data %>% # excludes observations
  filter(.cooksd<cuttoff)

nrow(nsfg_out2)/nrow(nsfg.clean) # check percent kept
# kept 99.96%

#rerun model
model4a<- glm(MORNPILL ~ CHSUPPOR + EVERPREG + ANYBC12 + RELIGION + age_cat, data=nsfg_out2, family="binomial")
summary(model4a)
odds.n.ends(model4a)

# The odds of never using emergency contraception in those who agree that single motherhood is acceptable is 1.50 times higher than those who strongly agree that single motherhood is acceptable after adjusting for history of pregnancy, use of regular birth control, religion, and age at first intercourse (95% CI = 1.30-1.72). 
# The odds of never using emergency contraception in those who disagree that single motherhood is acceptable is 2.25 times higher than those who strongly agree that single motherhood is acceptable after adjusting for history of pregnancy, use of regular birth control, religion, and age at first intercourse (95% CI = 1.77-2.89). 
# The odds of never using emergency contraception in those who strongly disagree that single motherhood is acceptable is 3.06 times higher than those who strongly agree that single motherhood is acceptable after adjusting for history of pregnancy, use of regular birth control, religion, and age at first intercourse (95% CI = 1.94-5.09).
# The odds of never using emergency contraception in those who neither agree nor disagree that single motherhood is acceptable is 1.70 times higher than those who strongly agree that single motherhood is acceptable after adjusting for history of pregnancy, use of regular birth control, religion, and age at first intercourse (95% CI = 0.91-3.48).

```

```{r}
#model fit assessment
# likelihood ratio test: compare two nested models
lrtest(model1, model3)

# Yes, it significantly improves model fit.
```

```{r}
#create figure 1
grViz("digraph flowchart {

      # node definitions with substituted label text
      node [fontname = Helvetica, shape = rectangle, fontsize=10] 
      # notes indicate how many boxes you will have in your diagram. Since I have two sets of exclusions, I will have three nodes.
      tab1 [label = '@@1'] # starting
      tab2 [label = '@@2'] # exclusion 1
      tab3 [label = '@@3'] # exclusion 2
      
      # edge definitions with the node IDs are used to indicate how the rectangle boxes flow from each other. This is a simple flow chart but I could create branching instead as below
      tab1 -> tab2 -> tab3 
}
      #This set of code provides the text in each rectangle box.
      [1]: 'Records received from NSFG in female respondent file n=6,141'
      [2]: 'Excluding 881 individuals with missing variables used in the analysis n=5,260'
      [3]: 'Excluding 2 individuals with influential points n=5,258'
      ")


```

```{r}
#create table 1
label(nsfg_out2$CHSUPPOR)<-"Supports single motherhood"
label(nsfg_out2$EVERPREG)<-"Ever been pregnant"
label(nsfg_out2$ANYBC12)<-"Use of regular birth control"
label(nsfg_out2$age_cat)<-"Age at first intercourse"
label(nsfg_out2$RELIGION)<-"Religion"
label(nsfg_out2$MORNPILL)<-"Ever used emergency contraception"
table1(~CHSUPPOR + EVERPREG + ANYBC12  + age_cat + RELIGION|MORNPILL, overall="Total", rowlabelhead="Variable", caption = "Emergency contraception use by individual factors", nsfg_out2)
```

